%% -*- mode: erlang; flycheck-mode: nil -*-
[_|Args] = init:get_plain_arguments(),          % rebar3 'commands' and options
lists:member("doc", Args) andalso application:ensure_all_started(inets),
case os:getenv("TRAVIS") of
    "true" ->
        JobId = os:getenv("TRAVIS_JOB_ID"),
        lists:keystore(coveralls_service_job_id, 1, CONFIG,
                       {coveralls_service_job_id, JobId});
    _ -> CONFIG
end.
